### ISSUE TITLE
[加入申请] 

### ISSUE THREAD

**Issue by Xiaoshen663** [ITCraftDevelopmentTeam/Forum#25]
### 群规协议

- [X] 我已阅读并同意以上协议。

### QQ号

2793489134

### 您的年龄

15

### 您从哪里得知 IT Craft Development Team？

qq群

### 为什么想加入 IT Craft Development Team？

闲

### 介绍一下你自己

会it CPP的一个臭打游戏的伞兵

**Comment by xxtg666** [comment]
不加qq群也行的，如果你只想进discord
