### ISSUE TITLE
[加入申请] 

### ISSUE THREAD

**Issue by ubby** [ITCraftDevelopmentTeam/Forum#27]
### 群规协议

- [X] 我已阅读并同意以上协议。

### QQ号

2509043002

### 您的年龄

19

### 您从哪里得知 IT Craft Development Team？

群聊

### 为什么想加入 IT Craft Development Team？

因为qq群公告里有所以我想加入

### 介绍一下你自己

rurdcrod
我是废物

**Comment by This-is-XiaoDeng** [comment]
年龄19是认真的吗（

**Comment by This-is-XiaoDeng** [comment]
你不是比我小吗（（

**Comment by muderstar** [comment]
Welcome！（
