### ISSUE TITLE
[加入申请] 

### ISSUE THREAD

**Issue by FZZkill** [ITCraftDevelopmentTeam/Forum#32]
### 群规协议

- [X] 我已阅读并同意以上协议。

### QQ号

3627035438

### 您的年龄

14

### 您从哪里得知 IT Craft Development Team？

QQ群友

### 为什么想加入 IT Craft Development Team？

我希望我可以在这里找到和我一样心怀梦想的人

### 介绍一下你自己

政治正确

**Comment by xxtg666** [comment]
你怎么还发申请
