### ISSUE TITLE
哼哼哼啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

### ISSUE THREAD

**Issue by xiaohhya1234MUA** [ITCraftDevelopmentTeam/Forum#38]
### 群规协议

- [X] 我已阅读并同意以上协议。

### QQ号

114514191

### 您的年龄

24

### 您从哪里得知 IT Craft Development Team？

computer

### 为什么想加入 IT Craft Development Team？

no all

### 介绍一下你自己

idk

**Comment by xxtg666** [comment]
> ### QQ号
> 
> 114514191
> 
> ### 您的年龄
> 
> 24

这部分内容不符合填写要求，不予通过
