### ISSUE TITLE
[加入申请] no chun

### ISSUE THREAD

**Issue by catmeowjiao** [ITCraftDevelopmentTeam/Forum#42]
### 群规协议

- [X] 我已阅读并同意以上协议。

### QQ号

3493487882

### 您的年龄

11

### 您从哪里得知 IT Craft Development Team？

QQ

### 为什么想加入 IT Craft Development Team？

no chun

**Comment by chun-awa** [comment]
乐

**Comment by xiaohhya1234MUA** [comment]
典

**Comment by This-is-XiaoDeng** [comment]
请不要重复提交申请
