### ISSUE TITLE
I'm looking for KMS maple farming macro

### ISSUE THREAD

**Issue by supertmt1** [ITCraftDevelopmentTeam/Forum#49]
### Group Agreement

- [X] I have read and agree to the terms above.

### QQ Number

tmt

### Your Age

37

### How did you learn about IT Craft Development Team?

naver learned

### Why do you want to join IT Craft Development Team?

dd

### Introduce Yourself

we are korean maple farmer.

**Comment by This-is-XiaoDeng** [comment]
We are glad to receive your application. Could you tell us more about yourself?
