### ISSUE TITLE
想加入[加入申请] 

### ISSUE THREAD

**Issue by frozenfish0x** [ITCraftDevelopmentTeam/Forum#56]
### 群规协议

- [X] 我已阅读并同意以上协议。

### QQ号

go语言

### 您的年龄

19

### 您从哪里得知 IT Craft Development Team？

github

### 为什么想加入 IT Craft Development Team？

想讨论学习技术。。。。。。。

### 介绍一下你自己

frozenfish2077

**Comment by This-is-XiaoDeng** [comment]
请尽快使用 Discord 帐号 `frozenfish2077` 加入我们的 [Discord 服务器](https://discord.gg/zcC5j9XAFG)，并凭此 Issue 向管理员获取身份组，IT Craft Development Team 欢迎您的加入
