### ISSUE TITLE
[加入申请] 

### ISSUE THREAD

**Issue by FortiterInRe** [ITCraftDevelopmentTeam/Forum#7]
### 群规协议

- [X] 我已阅读并同意以上协议。

### QQ号

2454213958

### 您的年龄

15

### 您从哪里得知 IT Craft Development Team？

他人介绍

### 为什么想加入 IT Craft Development Team？

学技术，~~舔大佬~~

**Comment by This-is-XiaoDeng** [comment]
我们已经同意您的申请。

请使用 `2454213958` 向 QQ 群 `701257458` 发送加群申请以加入 `IT Craft Development Team`
